import { useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { CldImage, CldUploadWidget } from 'next-cloudinary'

const inter = Inter({ subsets: ['latin'] })

const PAISAJE_BACKGROUNDS = [
  {
    id: 'cloudinary-project/cielo-colorido_y7ja9i',
    title: 'Cielo Colorido',
    width: 800,
    height: 600,
  },
  {
    id: 'cloudinary-project/siluetas-arboles_snqil1',
    title: 'Siluetas Arboles',
    width: 800,
    height: 600,
  },
  {
    id: 'cloudinary-project/Lago-hallstat_xqxufd',
    title: 'Lago hallstat',
    width: 800,
    height: 600,
  },
  {
    id: 'cloudinary-project/puesta-sol_od3zyq',
    title: 'Puesta de sol',
    width: 800,
    height: 600,
  },
  {
    id: 'cloudinary-project/paisaje-rocos_h1w7rz',
    title: 'Paisaje Rocoso',
    width: 800,
    height: 600,
  },
  {
    id: 'cloudinary-project/cielo-estrellado_mojttd',
    title: 'Cielo Estrellado',
    width: 800,
    height: 600,
  },
  {
    id: 'cloudinary-project/olas_sg1unz',
    title: 'Olas mar',
    width: 800,
    height: 600,
  },
]

export default function Home() {
  const [topText, setTopText] = useState('Cloudinary Project')
  const [bottomText, setBottomText] = useState('Bot lane')
  const [background, setBackground] = useState(PAISAJE_BACKGROUNDS[0].id)

  function handleOnTopTextChange(e) {
    setTopText(e.currentTarget.value)
  }
  function handleOnBottomTextChange(e) {
    setBottomText(e.currentTarget.value)
  }
  function handleOnBackgroundChange(id) {
    setBackground(id)
  }
  function handleOnBackgroundUpload(result) {
    setBackground(result.info.public_id)
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <div>
            <form>
              <div className={styles.inputOne} >
                <input type='text' name='top-text' onChange={handleOnTopTextChange} />
              </div>
              <div>
                <input type='text' name='bottom-text' onChange={handleOnBottomTextChange} />
              </div>

              <div className={styles.cardsImages}>
                <ul className={styles.backgrounds}>
                  {PAISAJE_BACKGROUNDS.map(({ id, title, width, height }) => {
                    return (
                      <li key={id} className={styles.imageCards} onClick={() => { handleOnBackgroundChange(id) }}>
                        <CldImage
                          src={id}
                          alt={title}
                          width={width}
                          height={height}
                          
                        />
                      </li>
                    )
                  })}
                </ul>
              </div>

              <div className={styles.buttons1}>
                <button className={styles.buttons}>Grayscale</button>
                <button className={styles.buttons}>Blur</button>
                <button className={styles.buttons}>Tint</button>
                <button className={styles.buttons}>Opacity</button>
                <button className={styles.buttons}>Zoom & pan</button>
                <button className={styles.buttons}>Pixelate</button>
              </div>

              <div>
                <CldUploadWidget uploadPreset="cloudinary-project-bg" onUpload={handleOnBackgroundUpload}>
                  {({ open }) => {
                    function handleOnClick(e) {
                      e.preventDefault();
                      open();
                    }
                    return (
                      <button onClick={handleOnClick}>
                        Upload an Image
                      </button>
                    );
                  }}
                </CldUploadWidget>
              </div>

            </form>

          </div>

          <div className={styles.image}>
            <CldImage
              src={background}
              width='320'
              height='320'
              crop='fill'
              alt='jugg will blade ur face'
              overlays={[
                {
                  width: 2670 - 20,
                  crop: 'fit',
                  position: {
                    x: 0,
                    y: 20,
                    gravity: 'north',
                  },
                  text: {
                    color: 'white',
                    fontFamily: 'Source Sans Pro',
                    fontSize: 40,
                    fontWeight: 'bold',
                    text: topText,
                    stroke: true,
                    border: '8px_solid_black'
                  }
                },
                {
                  width: 2670 - 20,
                  crop: 'fit',
                  position: {
                    x: 0,
                    y: 20,
                    gravity: 'south',
                  },
                  text: {
                    color: 'yellow',
                    fontFamily: 'Source Sans Pro',
                    fontSize: 40,
                    fontWeight: 'bold',
                    text: bottomText,
                    stroke: true,
                    border: '8px_solid_black'
                  }
                }
              ]}
            />

          </div>
        </div>
      </main>
    </>
  )
}
